# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

services:
  ckan:
    build:
      # The overridden file's directory development/external/ckan/contrib/docker is used as the base context
      context: ../../../../
      dockerfile: Dockerfile
    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
      - ../../ckanext-feedback:/usr/lib/ckan/venv/src/ckanext-feedback
    tty: true
      # Mount the root directory from within development/external/ckan/contrib/docker
      - ../../../../../:/opt/ckanext-feedback
      - /opt/ckanext-feedback/development/